/**
 * StudyGuide API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';
import { environment } from '../../../../environments/environment';
/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class TestApi {
    protected basePath = 'http://laceystudyguideapi.azurewebsites.net';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
         if (basePath) {
            this.basePath = basePath;
        } else {
            this.basePath = environment.apiBaseUrl;
        }
    }

    /**
     * 
     * 
     * @param id 
     */
    public DeleteStudyGuide (id: number, extraHttpRequestParams?: any ) : Observable<boolean> {
        const path = this.basePath + '/api/test/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiTestByIdDelete.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param id 
     */
    public GetById (id: number, extraHttpRequestParams?: any ) : Observable<models.ResponseTestViewModel> {
        const path = this.basePath + '/api/test/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
         headerParams.append('Content-Type', 'application/json');
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiTestByIdGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param value 
     */
    public AddStudyGuide (value?: models.TestViewModel, extraHttpRequestParams?: any ) : Observable<models.ResponseTestViewModel> {
        const path = this.basePath + '/api/test';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
         headerParams.append('Content-Type', 'application/json');
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(value);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param value 
     */
    public UpdateStudyGuide (value?: models.TestViewModel, extraHttpRequestParams?: any ) : Observable<models.ResponseTestViewModel> {
        const path = this.basePath + '/api/test';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(value);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param request 
     */
    public GetPaged (request?: models.PagedDataRequest, extraHttpRequestParams?: any ) : Observable<models.ResponseListTestViewModel> {
        const path = this.basePath + '/api/test/search';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
         headerParams.append('Content-Type', 'application/json');
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(request);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
